# Generated by Django 4.2.9 on 2024-09-07 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_name', models.CharField(max_length=30)),
                ('a_pic', models.ImageField(upload_to='')),
                ('a_BIO', models.TextField()),
                ('a_Nationality', models.CharField(max_length=30)),
                ('a_awards', models.CharField(max_length=30)),
                ('a_Gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=30)),
                ('a_birthday', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cityName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countryName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=30)),
                ('d_pic', models.ImageField(upload_to='')),
                ('d_BIO', models.TextField()),
                ('d_Nationality', models.CharField(max_length=30)),
                ('d_Awards', models.CharField(max_length=30)),
                ('d_gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=30)),
                ('d_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.city')),
                ('d_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='gener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=30)),
                ('Description', models.TextField()),
                ('Release_Year', models.DateTimeField()),
                ('poster', models.ImageField(upload_to='')),
                ('Trailer', models.URLField(blank=True, null=True)),
                ('Created_At', models.DateTimeField()),
                ('DIRECTOR', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.director')),
                ('Gener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.gener')),
                ('actors', models.ManyToManyField(to='myapp.actor')),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stateName', models.CharField(max_length=30)),
                ('countryID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_name', models.CharField(max_length=30)),
                ('u_DP', models.ImageField(upload_to='')),
                ('u_Gender', models.CharField(choices=[('1', 'Male'), ('2', 'Female')], max_length=30)),
                ('u_status', models.CharField(choices=[('0', 'IN-ACTIVE'), ('1', 'ACTIVE')], max_length=30)),
                ('u_date_joined', models.DateField()),
                ('u_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.city')),
                ('u_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country')),
                ('u_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.state')),
            ],
        ),
        migrations.CreateModel(
            name='watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Added_TO', models.CharField(max_length=30)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Rating', models.CharField(max_length=30)),
                ('Comment', models.CharField(max_length=30)),
                ('created_AT', models.DateTimeField()),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.movie')),
            ],
        ),
        migrations.AddField(
            model_name='director',
            name='d_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.state'),
        ),
        migrations.AddField(
            model_name='city',
            name='stateID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.state'),
        ),
        migrations.AddField(
            model_name='actor',
            name='a_city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.city'),
        ),
        migrations.AddField(
            model_name='actor',
            name='a_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.country'),
        ),
        migrations.AddField(
            model_name='actor',
            name='a_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.state'),
        ),
    ]
